spring:
  application:
    name: Student

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


  jpa:
    showSql: true

server:
  port: 8080

